all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /home/ubuntu/KAFKADEMO.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

zookeeper:
  hosts:
    ec2-3-145-88-253.us-east-2.compute.amazonaws.com:

kafka_broker:
  hosts:
    ec2-3-16-48-71.us-east-2.compute.amazonaws.com:
    ec2-3-142-134-4.us-east-2.compute.amazonaws.com:
    ec2-3-129-63-195.us-east-2.compute.amazonaws.com:

schema_registry:
  hosts:
    ec2-3-145-88-253.us-east-2.compute.amazonaws.com:

ksql:
  hosts:
    ec2-3-145-88-253.us-east-2.compute.amazonaws.com:

kafka_connect:
  hosts:
    ec2-3-145-88-253.us-east-2.compute.amazonaws.com:
      vars:
        kafka_connect_confluent_hub_plugins:
          - confluentinc/kafka-connect-datagen:0.4.0

control_center:
  hosts:
    ec2-3-145-88-253.us-east-2.compute.amazonaws.com: